import { EventEmitter, OnChanges, OnDestroy, OnInit } from '@angular/core';
import { LocaleData } from '@delon/theme';
import type { NgClassType } from 'ng-zorro-antd/core/types';
import { NoticeIconSelect, NoticeItem } from './notice-icon.types';
import * as i0 from "@angular/core";
export declare class NoticeIconComponent implements OnInit, OnChanges, OnDestroy {
    private readonly i18n;
    private readonly cdr;
    private i18n$?;
    locale: LocaleData;
    data: NoticeItem[];
    count?: number;
    loading: boolean;
    popoverVisible: boolean;
    btnClass?: NgClassType;
    btnIconClass?: NgClassType;
    centered: boolean;
    readonly select: EventEmitter<NoticeIconSelect>;
    readonly clear: EventEmitter<string>;
    readonly popoverVisibleChange: EventEmitter<boolean>;
    get overlayCls(): string;
    delayShow: boolean;
    onVisibleChange(result: boolean): void;
    onSelect(i: NoticeIconSelect): void;
    onClear(title: string): void;
    ngOnInit(): void;
    ngOnChanges(): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<NoticeIconComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<NoticeIconComponent, "notice-icon", ["noticeIcon"], { "data": { "alias": "data"; "required": false; }; "count": { "alias": "count"; "required": false; }; "loading": { "alias": "loading"; "required": false; }; "popoverVisible": { "alias": "popoverVisible"; "required": false; }; "btnClass": { "alias": "btnClass"; "required": false; }; "btnIconClass": { "alias": "btnIconClass"; "required": false; }; "centered": { "alias": "centered"; "required": false; }; }, { "select": "select"; "clear": "clear"; "popoverVisibleChange": "popoverVisibleChange"; }, never, never, true, never>;
    static ngAcceptInputType_count: unknown;
    static ngAcceptInputType_loading: unknown;
    static ngAcceptInputType_popoverVisible: unknown;
    static ngAcceptInputType_centered: unknown;
}
