import { ElementRef, OnDestroy, OnChanges, NgZone, ChangeDetectorRef, AfterViewInit, Renderer2 } from '@angular/core';
export declare class G2PieComponent implements OnDestroy, OnChanges, AfterViewInit {
    private el;
    private rend;
    private cd;
    private zone;
    private scroll$;
    private node;
    private chart;
    private initFlag;
    legendData: any[];
    animate: any;
    private _animate;
    color: string;
    subTitle: string;
    total: string;
    height: any;
    private _height;
    hasLegend: any;
    private _hasLegend;
    legendBlock: any;
    private _legendBlock;
    inner: number;
    padding: number[];
    percent: any;
    private _percent;
    tooltip: any;
    private _tooltip;
    lineWidth: any;
    private _lineWidth;
    select: any;
    private _select;
    data: Array<{
        x: number | string;
        y: number;
        [key: string]: any;
    }>;
    valueFormat: Function;
    colors: any[];
    constructor(el: ElementRef, rend: Renderer2, cd: ChangeDetectorRef, zone: NgZone);
    private setCls;
    private runInstall;
    private install;
    private installResizeEvent;
    _click(i: number): void;
    ngAfterViewInit(): void;
    ngOnChanges(): void;
    ngOnDestroy(): void;
}
