import { Platform } from '@angular/cdk/platform';
import { ChangeDetectorRef, EventEmitter, NgZone, OnDestroy, OnInit } from '@angular/core';
import { NumberInput } from '@delon/util/decorator';
import type { NzSafeAny } from 'ng-zorro-antd/core/types';
import { ChartEChartsService } from './echarts.service';
import { ChartECharts, ChartEChartsEvent, ChartEChartsOn, ChartEChartsOption } from './echarts.types';
import * as i0 from "@angular/core";
export declare class ChartEChartsComponent implements OnInit, OnDestroy {
    private srv;
    private cdr;
    private ngZone;
    private platform;
    static ngAcceptInputType_width: NumberInput;
    static ngAcceptInputType_height: NumberInput;
    private node;
    private destroy$;
    private _chart;
    private _theme?;
    private _initOpt?;
    private _option;
    _width: string;
    _height: string;
    set width(val: NumberInput);
    set height(val: NumberInput);
    set theme(value: string | Record<string, unknown> | null | undefined);
    set initOpt(value: NzSafeAny);
    set option(value: ChartEChartsOption);
    on: ChartEChartsOn[];
    readonly events: EventEmitter<ChartEChartsEvent>;
    get chart(): ChartECharts | null;
    loaded: boolean;
    constructor(srv: ChartEChartsService, cdr: ChangeDetectorRef, ngZone: NgZone, platform: Platform);
    private emit;
    private load;
    install(): this;
    destroy(): this;
    setOption(option: ChartEChartsOption, notMerge?: boolean, lazyUpdate?: boolean): this;
    ngOnInit(): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ChartEChartsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ChartEChartsComponent, "chart-echarts, [chart-echarts]", ["chartECharts"], { "width": { "alias": "width"; "required": false; }; "height": { "alias": "height"; "required": false; }; "theme": { "alias": "theme"; "required": false; }; "initOpt": { "alias": "initOpt"; "required": false; }; "option": { "alias": "option"; "required": false; }; "on": { "alias": "on"; "required": false; }; }, { "events": "events"; }, never, never, true, never>;
}
