"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
function genSharedLibsAutoFile(options, host, icons) {
    const content = `/*
* Automatically generated by 'ng g ng-alain:plugin import'
* @see https://ng-alain.com/cli/plugin#import
*/

import {
  ${icons.join(',\n  ')}
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  ${icons.join(',\n  ')}
];
`;
    const savePath = options.sourceRoot + `/app/shared/shared-libs-auto.ts`;
    if (host.exists(savePath)) {
        host.overwrite(savePath, content);
    }
    else {
        host.create(savePath, content);
    }
}
function pluginModule(options) {
    return (host, context) => {
        console.log(`Analyzing files...`);
        console.log(`\n\n`);
        // console.log(`生成成功，如果是首次运行，需要手动引用，参考：https://ng-alain.com/theme/icon/zh`);
        // console.log(`Finished, if it's first run, you need manually reference it, refer to: https://ng-alain.com/theme/icon/en`);
        console.log(`\n\n`);
    };
}
exports.pluginModule = pluginModule;
//# sourceMappingURL=plugin.module.js.map