import { Direction } from '@angular/cdk/bidi';
import { AfterViewInit, EventEmitter, OnDestroy } from '@angular/core';
import { OnboardingConfig, OnboardingItem, OnboardingOpType } from './onboarding.types';
import * as i0 from "@angular/core";
export declare class OnboardingComponent implements OnDestroy, AfterViewInit {
    private readonly el;
    private readonly platform;
    private readonly cdr;
    private readonly doc;
    private time;
    private prevSelectorEl?;
    config: OnboardingConfig;
    item: OnboardingItem;
    active: number;
    max: number;
    readonly op: EventEmitter<OnboardingOpType>;
    running: boolean;
    dir: Direction;
    private popover;
    get first(): boolean;
    get last(): boolean;
    private _getDoc;
    private _getWin;
    private getLightData;
    ngAfterViewInit(): void;
    private scroll;
    updateRunning(status: boolean): void;
    private updatePosition;
    private updatePrevElStatus;
    to(type: OnboardingOpType): void;
    handleMask(): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<OnboardingComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<OnboardingComponent, "onboarding", never, {}, {}, never, never, true, never>;
}
